import { useState } from "react";
import { Toaster } from "sonner";
import imgLogo from "../imports/Login/cc2e61b111cffc63dc0e0ab4b569556ebceef676.png";
import Signup from "./Signup";
import ForgotPassword from "./ForgotPassword";
import MainPage from "./MainPage";
import HistoryPage from "./HistoryPage";
import ProfilePage from "./ProfilePage";
import { apiGet, apiPost } from "./api";

export interface Account {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  password: string;
}

export interface PurchasedTicket {
  eventName: string;
  category: string;
  date: string;
  location: string;
  price: string;
  totalPrice: string;
  quantity: number;
  purchasedOn: string;
  isUpcoming: boolean;
  ticketCode: string;  // unique per purchase, generated by the database
  holderName: string;
}

type View = "login" | "signup" | "forgot" | "main" | "history" | "profile";

export default function App() {
  const [view, setView] = useState<View>("login");

  // Accounts now live in the MySQL `users` table — the API is the
  // source of truth, so we no longer keep a local accounts list.
  const [currentAccount, setCurrentAccount] = useState<Account | null>(null);
  const [tickets, setTickets] = useState<PurchasedTicket[]>([]);

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Pull this user's ticket history from the database (tickets table)
  async function loadTickets(accountEmail: string): Promise<PurchasedTicket[]> {
    try {
      const res = await apiGet<{ success: boolean; tickets: any[] }>("get_tickets.php", {
        email: accountEmail,
      });
      if (!res.success) return [];
      return res.tickets.map((t) => ({
        eventName: t.eventName,
        category: t.category,
        date: t.date,
        location: t.location,
        price: t.price,
        totalPrice: t.totalPrice,
        quantity: t.quantity,
        purchasedOn: t.purchasedOn,
        isUpcoming: true, // history view shows purchase date, not event status
        ticketCode: t.ticketCode,
        holderName: t.holderName,
      }));
    } catch {
      return [];
    }
  }

  // Called by Signup.tsx after the form validates locally.
  // Persists the new account to the database via api/signup.php.
  async function handleRegister(account: Account) {
    setError("");
    try {
      const res = await apiPost<{ success: boolean; message: string }>("signup.php", {
        firstName: account.firstName,
        lastName: account.lastName,
        email: account.email,
        phone: account.phone,
        password: account.password,
      });
      if (!res.success) {
        setError(res.message || "Could not create account.");
        return;
      }
      setView("login");
    } catch {
      setError("Could not reach the server. Make sure XAMPP (Apache + MySQL) is running.");
    }
  }

  // Called after PaymentModal confirms a purchase. Sends the payment/
  // ticket details to api/purchase_ticket.php, which INSERTs the row
  // into the `tickets` table and decrements event availability.
  async function handleBuy(eventId: number, holderName: string, quantity: number) {
    if (!currentAccount) return;
    try {
      const res = await apiPost<{ success: boolean; message: string; ticket?: any }>(
        "purchase_ticket.php",
        {
          eventId,
          email: currentAccount.email,
          holderName,
          quantity,
        }
      );
      if (!res.success) {
        console.error("Purchase failed:", res.message);
        return;
      }
      // Refresh history so it reflects the new ticket_code from the database
      const updated = await loadTickets(currentAccount.email);
      setTickets(updated);
    } catch {
      console.error("Could not reach the server while purchasing the ticket.");
    }
  }

  // Clear user state on logout
  const nav = (v: View) => {
    if (v === "login") {
      setTickets([]);
      setCurrentAccount(null);
    }
    setView(v);
  };

  // Called from ForgotPassword's final step. Updates the password
  // in the database via api/forgot_password.php (action: "reset").
  async function handleResetPassword(resetEmail: string, newPassword: string) {
    await apiPost("forgot_password.php", {
      action: "reset",
      email: resetEmail,
      newPassword,
    });
    nav("login");
  }

  // Checks if an email exists in the database (step 1 of forgot-password flow)
  async function handleCheckEmail(checkEmail: string): Promise<boolean> {
    try {
      const res = await apiPost<{ success: boolean }>("forgot_password.php", {
        action: "check",
        email: checkEmail,
      });
      return res.success;
    } catch {
      return false;
    }
  }

  if (view === "signup") return <Signup onRegister={handleRegister} onBack={() => nav("login")} />;
  if (view === "forgot")
    return (
      <ForgotPassword
        onCheckEmail={handleCheckEmail}
        onResetPassword={handleResetPassword}
        onBack={() => nav("login")}
      />
    );
  if (view === "main")
    return (
      <>
        <MainPage
          onNavigate={nav}
          onBuy={handleBuy}
          holderName={currentAccount ? `${currentAccount.firstName} ${currentAccount.lastName}`.trim() : ""}
        />
        <Toaster position="top-center" richColors />
      </>
    );
  if (view === "history")
    return (
      <>
        <HistoryPage
          onNavigate={nav}
          tickets={tickets}
          holderName={currentAccount ? `${currentAccount.firstName} ${currentAccount.lastName}`.trim() : ""}
        />
        <Toaster position="top-center" richColors />
      </>
    );

  // Called from ProfilePage's "Save" action. Updates the account in
  // the database via api/update_profile.php.
  async function handleUpdateAccount(updated: Account) {
    if (!currentAccount) return;
    try {
      const res = await apiPost<{ success: boolean; message: string; account?: Account }>(
        "update_profile.php",
        {
          currentEmail: currentAccount.email,
          firstName: updated.firstName,
          lastName: updated.lastName,
          email: updated.email,
          phone: updated.phone,
        }
      );
      if (!res.success) {
        console.error("Profile update failed:", res.message);
        return;
      }
      setCurrentAccount({ ...updated, password: currentAccount.password });
    } catch {
      console.error("Could not reach the server while updating the profile.");
    }
  }

  if (view === "profile")
    return (
      <>
        <ProfilePage onNavigate={nav} account={currentAccount} onUpdateAccount={handleUpdateAccount} />
        <Toaster position="top-center" richColors />
      </>
    );

  // Login form submit — verifies credentials against the database via
  // api/login.php, then loads this user's ticket history.
  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!email.trim() || !password.trim()) {
      setError("Please enter your email and password.");
      return;
    }
    setSubmitting(true);
    setError("");
    try {
      const res = await apiPost<{ success: boolean; message: string; account?: Account }>("login.php", {
        email: email.trim(),
        password,
      });
      if (!res.success || !res.account) {
        setError(res.message || "Invalid email or password.");
        return;
      }
      const account: Account = { ...res.account, password };
      setCurrentAccount(account);
      setTickets(await loadTickets(account.email));
      nav("main");
    } catch {
      setError("Could not reach the server. Make sure XAMPP (Apache + MySQL) is running.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="h-screen w-full bg-white overflow-y-auto" style={{ fontFamily: "'Poppins', sans-serif" }}>
      <div className="min-h-full flex flex-col items-center justify-center py-6 px-4">
        {/* Logo */}
        <div className="mb-3 w-[180px] sm:w-[220px] overflow-hidden shrink-0" style={{ height: "clamp(90px, 13vw, 160px)" }}>
          <img src={imgLogo} alt="MyTown logo" className="w-full h-auto object-contain" />
        </div>

        {/* Login card */}
        <div className="relative z-10 w-full max-w-[420px] rounded-[28px] border border-[#5d5b5b] bg-[#fffbfb] px-5 sm:px-8 py-4">
          <h1 className="text-center font-semibold mb-0.5" style={{ color: "#78AAD7", fontSize: 28, lineHeight: 1.2 }}>LOGIN</h1>
          <p className="text-center mb-3" style={{ color: "#5d5b5b", fontSize: 14, fontWeight: 500 }}>Welcome back!</p>

          <form onSubmit={handleSubmit} className="flex flex-col gap-2.5">
            <input
              type="email" placeholder="Email" value={email}
              onChange={(e) => { setEmail(e.target.value); setError(""); }}
              className="w-full rounded-[14px] border border-black bg-transparent px-3 py-2 outline-none focus:border-[#78AAD7] transition-colors"
              style={{ color: "#5d5b5b", fontSize: 14, fontWeight: 500, fontFamily: "'Poppins', sans-serif" }}
            />
            <div className="relative">
              <input
                type={showPassword ? "text" : "password"} placeholder="Password" value={password}
                onChange={(e) => { setPassword(e.target.value); setError(""); }}
                className="w-full rounded-[14px] border border-black bg-transparent px-3 py-2 pr-10 outline-none focus:border-[#78AAD7] transition-colors"
                style={{ color: "#5d5b5b", fontSize: 14, fontWeight: 500, fontFamily: "'Poppins', sans-serif" }}
              />
              <button
                type="button"
                onClick={() => setShowPassword((v) => !v)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-[#78AAD7] transition-colors"
                aria-label="Toggle password visibility"
              >
                {showPassword ? (
                  <svg width="18" height="18" fill="none" viewBox="0 0 24 24">
                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    <circle cx="12" cy="12" r="3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                ) : (
                  <svg width="18" height="18" fill="none" viewBox="0 0 24 24">
                    <path d="M17.94 17.94A10.07 10.07 0 0112 20c-7 0-11-8-11-8a18.45 18.45 0 015.06-5.94M9.9 4.24A9.12 9.12 0 0112 4c7 0 11 8 11 8a18.5 18.5 0 01-2.16 3.19M1 1l22 22" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                )}
              </button>
            </div>
            <div className="flex justify-end">
              <button type="button" onClick={() => nav("forgot")}
                className="text-[#5d5b5b] hover:text-[#78AAD7] transition-colors bg-transparent border-none p-0 cursor-pointer"
                style={{ fontSize: 12, fontWeight: 500, fontFamily: "'Poppins', sans-serif" }}>
                Forgot Password?
              </button>
            </div>
            {error && <p className="text-red-500 text-xs text-center" style={{ fontFamily: "'Poppins', sans-serif" }}>{error}</p>}
            <button type="submit" disabled={submitting}
              className="w-full rounded-[14px] bg-[#78AAD7] py-2 text-white hover:bg-[#6299c6] active:bg-[#5888b5] transition-colors disabled:opacity-60"
              style={{ fontSize: 14, fontWeight: 500, fontFamily: "'Poppins', sans-serif" }}>
              {submitting ? "LOGGING IN..." : "LOGIN"}
            </button>
          </form>

          <div className="my-3 border-t border-[#5d5b5b]" />
          <p className="text-center" style={{ color: "#5d5b5b", fontSize: 12, fontWeight: 500 }}>
            Dont have an account yet?{" "}
            <button onClick={() => nav("signup")}
              className="font-bold hover:text-[#78AAD7] transition-colors bg-transparent border-none p-0 cursor-pointer"
              style={{ fontFamily: "'Poppins', sans-serif", fontSize: "inherit", color: "inherit" }}>
              Register here.
            </button>
          </p>
        </div>
      </div>
    </div>
  );
}
